FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install -g @angular/cli@19.2.13
RUN npm install --legacy-peer-deps
COPY . .
RUN ng build --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/helloangularnet.client/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80