version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # aquí defines la cadena de conexión a la base de datos en la nube
      - ConnectionStrings__Context=Host=35.184.155.33;Port=5432;Database=postgres;Username=postgres;Password=Createga@123
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
