version: '3.9'

services:
  angularnet:
    build: .
    container_name: angularnet
    ports:
      - "5000:8080"   # localhost:5000 -> contenedor:8080
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - myDB

  myDB:
    image: postgres:15
    container_name: my-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=createga
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=prueba_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - app-network
  
  pdAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
      - myDB
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=createga@prueba.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
